app.transactions.file-name=transactions.json
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer_db
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
# Wyświetla zapytania w konsoli
spring.jpa.show-sql=true
# Formatuje SQL, żeby był czytelny, a nie w jednej linii
spring.jpa.properties.hibernate.format_sql=true
# Pokazuje wartości parametrów (zamiast znaków zapytania '?')
logging.level.org.hibernate.orm.jdbc.bind=trace