app.transactions.file-name=transactions.json
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer_db
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true